Try to fix a failing docs build on readthedocs.io
On Build #7951881 of commit 1eace97d25c3 at
https://readthedocs.org/projects/wrapitup/builds/7951881/
it was failing with a traceback that read, in part:

  ...
  File "conf.py", line 26, in <module>
    from wrapitup import __version__
  ...
  File "<...>/wrapitup/_catch_signals.py", line 208, in catch_signals
    exc_type: typing.Optional[typing.Type[_ExcType]],
  File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
    return Union[arg, type(None)]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "<...>/wrapitup/envs/latest/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument

What's weird is that building on Python 3.5 worked just fine on Travis
at https://travis-ci.org/wkschwartz/wrapitup/jobs/442353110

Rather than try to reproduce the exact environment that readthedocs.io
is running, I'm just simplifying the type signature of __exit__ where
the error occurred. Technically it was more accurate before this change
but since user code doesn't directly call __exit__, the type signature
is less important.